### ISSUE TITLE
Landing page / make more beautiful

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#101]
I think the landing page of https://sirix.io could get some love: 

https://github.com/sirixdb/sirixdb.github.io/blob/master/index.html

**Comment by Alais29** [comment]
Hi! I would love to work on this issue. If you could please direct me to where the current index and css files are I'll start working on it ASAP :)

**Comment by JohannesLichtenberger** [comment]
Hi, thanks so much. The repository: https://github.com/sirixdb/sirixdb.github.io

**Comment by Alais29** [comment]
Got it, thanks!

**Comment by JoelLau** [comment]
@Alais29 I seem to have the skillset as you do! let me know if there's any way I can help

**Comment by Alais29** [comment]
Hi @JohannesLichtenberger I was going to start working on the project now but I seem to have some issues getting it to run on my computer. For what I could check on the repository, It's built with Ruby and Jekyll (please correct me if I'm wrong since I don't really know anything about ruby), I tried installing Ruby and Jekyll on my pc by following the instructions here https://jekyllrb.com/docs/installation/windows/ and then tried to run the project following these instructions https://jekyllrb.com/docs/ but when I run the "bundle exec jekyll serve" command this is what i get: 

![image](https://user-images.githubusercontent.com/28829550/66277138-86611000-e870-11e9-9b33-10b76244d0f6.png)

Not really sure what the problem may be :( I'd really appreciate if you could give me some guidance since, like i said, I'm not familiar with Ruby (or Jekyll). Thanks in advance!

Also @JoelLau I wouldn't mind your help :) as soon as I can get the project to run and start making some changes I'll let you know what you could help me with :)

**Comment by JohannesLichtenberger** [comment]
Does `bundle install` help?

**Comment by Alais29** [comment]
@JohannesLichtenberger That did it!! Thanks :)

**Comment by JohannesLichtenberger** [comment]
Cool, great :-)

**Comment by JohannesLichtenberger** [comment]
Still working on this? :-) have a nice weekend

**Comment by Alais29** [comment]
Hi @JohannesLichtenberger Yes! I'm sorry, it was a really busy week for me so I wasn't able to work much on this, but I'm still on it, I'll let you know when it's ready, hopefully by this week :)

**Comment by Alais29** [comment]
Actually, maybe by tonight or tomorrow I'll have some changes done 👍

**Comment by Alais29** [comment]
Hi @JohannesLichtenberger I just made the pull request on the other repository, please let me know if you like the changes :)

**Comment by JohannesLichtenberger** [comment]
Yes, it's great :+1:
