### ISSUE TITLE
Provide a memory mapped file backend

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#115]
In addition to the `RandomAccessFile` backend we could use a memory mapped file backend, preferably using a framework or something like that which is proven and stable.

**Comment by EmilGedda** [comment]
Is this issue is still active? If so, I (or rather my group) would like to try to implement this.

Our additions will be in the `org.sirix.file` package and includes adding a `MemoryMapped` version of the already existing `Reader`, `Storage`, and `Writer` classes for the existing file backend and unifying the two different backends behind one interface. We will also take a look at the tests relating to the different storage backends, possibly lifting a few interfaces to help swapping out the concrete implementations during testing further down the line. 

We will most likely have a bunch of questions this coming week. The first question is how we would enable this feature. What do you think about having a command line flag such as `--mmap` or `--memory-map`?

**Comment by JohannesLichtenberger** [comment]
That would be awesome. To be honest, I'm not entirely sure which benefits/drawbacks memory mapped files have, but I guess we should map the whole file at once opposed to only page-fragment regions. However, the file can get very large, at least in theory. I was able to import a 4 GB JSON file, but obviously I envision much bigger files, as it's more of a hybrid in-memory / on-flash drive DBMS.

I'm also not sure if in that case we should drop the caches (BufferManager) all-together only adding the in-memory page references. Currently in-memory as well as caches are used to share the pages between read-only transactions and to null-out the in-memory page-reference once a cache entry has to be evicted.

**Comment by JohannesLichtenberger** [comment]
Regarding the configuration it's in the ResourceConfiguration :-)
and in org.sirix.io.StorageType

**Comment by JohannesLichtenberger** [comment]
Ah, and we already have a Reader and a Writer interface

**Comment by JohannesLichtenberger** [comment]
BTW: what's also interesting will be Byte Addressable NVM as for instance Intel Opthane Memory. I think it's an especially good fit due to fine granular access and even way faster random reads in comparison with SSDs. SirixDB does not store the whole database-pages during commits. It depends on the versioning algorithm, but usually only changed nodes + a few more are stored. This means that Sirix has to read a few page-fragments from random positions in the file to reconstruct a full page in-memory (might be done in parallel if hardware permits in the future).

Thus, I think due to heavy random reading (and log-structured, sequential writes) plus only storing variable sized page fragments it's a perfect fit.

https://openjdk.java.net/jeps/352

Also a new Memory API is coming with Java 14.

**Comment by mikkar2** [comment]
Unfortunately we could not resolve this issue due to limited time, lacking documentation and bugs in our code which we couldn’t solve due to the lack of tests close to the functionality we were trying to implement. We think we are close to a solution and hopefully someone else can take over and fix the bugs we were unable to solve. 

link to work in progress:  https://github.com/soffan20/sirix/pull/74

Documentation MemoryMap Implementation 
The current implementation will do all read/writes directly to disc when managing the database. The main idea with this implementation is to use MappedByteBuffer which will load a file into memory that can be accessed faster.


MemoryMap

MemoryMap is the equivalent of FileStorage with methods createReader and createWriter. The MemoryMap works as a virtual file which is instead stored in the RAM> These methods return a MemoryMapReader and MemoryMapWriter respectively, instead of the FileReader and FileWriter that FileStorage returns. MemoryMap uses composition with FileStorage in order to use the functions that don’t need to be modified.

MemoryMapWriter

MemoryMapWriter is the equivalent of FileWriter. It has the same functionality as FileWriter except for writing to RAM instead of a file on the harddrive. A MappedByteBuffer is used to read and write from RAM instead of using the seek, get and put methods of RandomAccessFile. 

MemoryMapReader

MemoryMapReader is the equivalent of FilerReader. It has the same functionality as FileReader except for reading from RAM instead of a file on the harddrive. A MappedByteBuffer is used to read from RAM instead of using the seek and get methods of RandomAccessFile. 

MappedByteBufferHandler 

MappedByteBufferHandler is used to handle the writing and reading to and from files to make sure that the offset and size of the buffer are correctly handled. It implements all the necessary methods that are needed for reading and writing. It also makes sure that the the file which is held in memory is synchronized so that several threads accessing the file will see the same thing.

**Comment by JohannesLichtenberger** [comment]
Great work so far. I hope you don't delete the work...

However, due to the limitations of MappedByteBuffers (2Gb for instance), I think we should switch to Java14 as soon as it's out and use the Foreign Memory Access API:

https://www.youtube.com/watch?v=NwXzT8T6mb8
