### ISSUE TITLE
Making keeping track of the childCount of each node configurable

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#191]
To further reduce storage space we can make it optional to keep track of the `childCount` of nodes.

**Comment by punit-kulal** [comment]
I am thinking of working on this issue next, can you tell me how should I go about it

**Comment by JohannesLichtenberger** [comment]
You can introduce a configuration parameter in `ResourceConfiguration`, something like `storeChildCount(boolean)`. Then you'd have to check in `JsonNodeTrx` and in `XmlNodeTrx` where the childCount is set and make it dependant on the resource config parameter. You'd also have to check in NodeKind where the StructNodeDelegate is serialized/deserialized. This touches quiet some layers, but I guess it's a good start to get to know the code base better. I also wanted to split these big transactions sometimes in the future.

**Comment by JohannesLichtenberger** [comment]
@punit-kulal let me know if I can give you further guidance...

**Comment by punit-kulal** [comment]
@JohannesLichtenberger  I was trying to read up the structure and this is what I could infer: When we say keeping track of childCount configurable to save space, what we essentially mean is not serializing/deserializing the childCount property. If the user has a configuration which tells  not to track the childCount property. How do we serialize, if the configuration changes between two different sessions.
Seems like the configuration should rather be in Database configuration since if node child Count is configured non trackable we won't able to track it again. Correct me if I am wrong

**Comment by JohannesLichtenberger** [comment]
Hey, it should be configurable in the `ResourceConfiguration`, that is when a resource is created :-)

**Comment by JohannesLichtenberger** [comment]
Do you need further help? :-)

**Comment by punit-kulal** [comment]
I am a bit occupied with other priorities, I have started making the changes, will definitely ask if I hit a roadblock

**Comment by JohannesLichtenberger** [comment]
okay, sounds great

**Comment by punit-kulal** [comment]
What's the use of difference between child count and descendent count? I could see them being  used along with childCount operations, but couldn't understand the use for it as it is not being used consistently in XML and JSON Node.

**Comment by JohannesLichtenberger** [comment]
- `childCount` is the number of immidiate children
- `descendantCount` is the number of nodes in the whole subtree

**Comment by JohannesLichtenberger** [comment]
HTH, do you need further help?

**Comment by punit-kulal** [comment]
No, that would be it
