### ISSUE TITLE
Implement a JsonStreamingShredder based on Vert.x JSON streaming parser

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#282]
Thus, we can omit storing first a temp JSON file in the HTTP-Server:

https://vertx.io/docs/apidocs/io/vertx/core/parsetools/JsonParser.html

**Comment by JPDSousa** [comment]
Hey @JohannesLichtenberger can you elaborate here? Can't find a reference to this "temp JSON file"

**Comment by mosheduminer** [comment]
@JPDSousa when a resource (or multiple resources) are uploaded to the API server, the API server first writes the data to a temporary file, and when the data is fully loaded, it is then loaded into a SirixDB resource. You can see this happening in [this method](https://github.com/sirixdb/sirix/blob/fa3529b514c56fa5ca52e72b5d7731bb9fa05cf6/bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/json/JsonCreate.kt#L129) for JSON resources, and in [this method](https://github.com/sirixdb/sirix/blob/fa3529b514c56fa5ca52e72b5d7731bb9fa05cf6/bundles/sirix-rest-api/src/main/kotlin/org/sirix/rest/crud/xml/XmlCreate.kt#L118) for XML resources.

The alternative is to somehow parse the file while the data is still being uploaded (though I don't know what exactly would need to be changed in the internals). I think this should have the advantage of faster uploads, as well as a nicer experience on the GUI frontend (currently, there is a meter showing how much of the file was uploaded, but there is a wait (for larger files) after the upload is completed, before the HTTP request completes, because SirixDB now needs to parse the file).

**Comment by JohannesLichtenberger** [comment]
As @mosheduminer already said, we can skip the part where we first store the whole JSON data in a temporary file and then import the file in SirixDB. Instead, we could use the Vert.x streaming JSON parser to omit the creation of the temp file in the first place and to stream data directly into a SirixDB database resource.

**Comment by JohannesLichtenberger** [comment]
@JPDSousa, I think we have to refactor the rest-api module at some point, as almost all stuff is simply duplicated between the XML databases and JSON databases... it basically was a quick hack to get the API server up and running (plus I wanted to try Kotlin + Coroutines and Vert.x ;). I think we more or less are able to encapsulate the functionality for both database types again in one class (Get, Update, Delete...).

**Comment by mosheduminer** [comment]
If a refactor of the REST module is done, please keep ib mind fhe open issues related to it. Such as #254, #286, #319.
