### ISSUE TITLE
LZ4 compression for page fragments not working

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#559]
We should investigate performance with LZ4 vs. Snappy (should be slightly better). However, the added LZ4 compressor somehow throws an IOException currently (which can be changed in `ResourceConfiguration` for the default).

**Comment by yash29896** [comment]
Can I Work on this ?

**Comment by yash29896** [comment]
How can I recreate this?

Currently I've brought up the sirix-keycloack and the sirix-server with the steps mentioned in 

"Start the SirixDB HTTP-Server and the Keycloak-Container using docker compose"

And I've changed the following in ResourceConfiguration 

`byteHandler = new ByteHandlerPipeline(new SnappyCompressor());//new LZ4Compressor()); // new Encryptor(path));`
`byteHandler = new ByteHandlerPipeline(new LZ4Compressor());//new LZ4Compressor()); // new Encryptor(path));`

**Comment by JohannesLichtenberger** [comment]
You can simply run the tests from your IDE for instance

**Comment by JohannesLichtenberger** [comment]
Meaning without docker / docker compose you can simply run tests in sirix-core and they'll fail.

**Comment by yash29896** [comment]
Yes this is the exception right ?

`java.io.IOException: Stream ended prematurely
org.sirix.exception.SirixIOException: java.io.IOException: Stream ended prematurely
..
Caused by: java.io.IOException: Stream ended prematurely
at net.jpountz.lz4.LZ4FrameInputStream.readInt(LZ4FrameInputStream.java:245)`

**Comment by JohannesLichtenberger** [comment]
Yes

**Comment by yash29896** [comment]
@JohannesLichtenberger

Seems Like the problem is with the following method. frameInfo.isFinished() seems to always be false

LZ4FrameInputStream.read() (3rd party)

```java
public int read() throws IOException {
    while (!firstFrameHeaderRead || buffer.remaining() == 0) {
       //frameInfo.isFinished() seems to always be false
      if (!firstFrameHeaderRead || frameInfo.isFinished()) {
        if (firstFrameHeaderRead && readSingleFrame) {
          return -1;
        }
	if (!nextFrameInfo()) {
	 // Should have returned -1 from here
	  return -1;
	}
      }
      // Enters here and produces and exception
      readBlock(); 
    }
    return (int)buffer.get() & 0xFF;
  }
```

Input Byte Array in the Unit Test is 
[4, 34, 77, 24, 96, 112, 115, 6, 0, 0, -128, 3, 0, 1, 0, 0, 0]     

It is read in the following manner
4, 34, 77, 24 -> Magic number
96, 112, 115 -> Headers
6, 0, 0, -128 -> more metadata 
3, 0, 1, 0, 0, 0 -> Uncompressed data

```java
  private void readBlock() throws IOException {
    int blockSize = readInt(in);    // Reads 6, 0, 0, -128
    final boolean compressed = (blockSize & LZ4FrameOutputStream.LZ4_FRAME_INCOMPRESSIBLE_MASK) == 0;
    blockSize &= ~LZ4FrameOutputStream.LZ4_FRAME_INCOMPRESSIBLE_MASK;     //blocksize is 6 6

    // Check for EndMark
    if (blockSize == 0) {
      if (frameInfo.isEnabled(LZ4FrameOutputStream.FLG.Bits.CONTENT_CHECKSUM)) {
        final int contentChecksum = readInt(in);
        if (contentChecksum != frameInfo.currentStreamHash()) {
          throw new IOException("Content checksum mismatch");
        }
      }
      if (frameInfo.isEnabled(LZ4FrameOutputStream.FLG.Bits.CONTENT_SIZE) && expectedContentSize != totalContentSize) {
	throw new IOException("Size check mismatch");
      }
      frameInfo.finish();                // THIS IS SKIPPED
      return;
    }

...

    int offset = 0;
    while (offset < blockSize) {
     // Reads  [3,0,1,0,0,0]
      final int lastRead = in.read(tmpBuffer, offset, blockSize - offset);
      if (lastRead < 0) {
        throw new IOException(PREMATURE_EOS);
      }
      offset += lastRead;
    }
..........
```
Can this be an issue with the frame format ?  Cause frameInfo.finish() is getting skipped

**Comment by JohannesLichtenberger** [comment]
Not sure, but I guess it has to be an issue with a wrong usage in our Sirix byte handler, somehow...

**Comment by JohannesLichtenberger** [comment]
We have to use `LZ4BlockInputStream/LZ4BlockOutputStream`...
